services:
  - type: web
    name: arolink-catcher
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TG_API_ID
        sync: false
      - key: TG_API_HASH
        sync: false
      - key: TG_SESSION
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false
      - key: BOT_USER_ID
        sync: false
      - key: BYPASS_BOT
        sync: false
